name: GitHub Actions Build and Deploy

on:
  push:
      branches:
        -  main
  # 手动运行工作流程（workflow_dispatch 事件触发器配置后可以在actions下手动运行工作流）
permissions:
    contents: write
  
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest  #指定服务器的运行环境：最新版本ubuntu
    steps:
      # 使用actions/checkout@v4 库拉取代码到 ubuntu 上
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # 设置node的版本
      - name: Use Node.js
        # 使用 actions/setup-node@v3 库安装 nodejs，with 提供了一个参数 node-version 表示要安装的 nodejs 版本
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

       
      # 安装依赖
      # Install dependencies
      - name: Install Dependencies
        run: 
            corepack enable
            pnpm install --frozen-lockfile 

      # 运行构建脚本
      # Run the build script
      - name: Build VuePress site
        run:  
            pnpm add vitepress-auto-sidebar-plugin --save-dev
            pnpm run docs:build
            > docs/.vitepress/dist/.nojekyll

      # 部署到GitHub Pages - 也就是将打包内容发布到GitHub Pages
      - name: Deploy
        # 使用别人写好的 actions去部署（将打包文件部署到指定分支上）
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        # 自定义环境变量
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
